### ISSUE TITLE
Segfault when interfacing with libcurl (Ubuntu 18.04)

### ISSUE THREAD

**Issue by unilock** [tihmstar/tsschecker#139]
I'm running tsschecker 277 (ee5f44c) on GalliumOS 3.0 (Ubuntu 18.04 Bionic).

When I use tsschecker to do anything that requires libcurl (i.e. interfacing with Apple's servers), it segfaults. Examples:

> $ tsschecker -d iPhone3,1 --list-ios
Version: ee5f44c2351320fee43e66fc81f5812ba3992d2c - 277
Segmentation fault (core dumped)

> $ tsschecker -d iPad4,4 -e [ECID] -s -i 12.3
Version: ee5f44c2351320fee43e66fc81f5812ba3992d2c - 277
Segmentation fault (core dumped)

I've read that there are some issues with libcurl and Ubuntu 18.04 when it comes to tsschecker, and that these segfaults may be symptoms of those issues. I followed the instructions [here](https://dev.to/jake/using-libcurl3-and-libcurl4-on-ubuntu-1804-bionic-184g) to "install" libcurl3 alongside libcurl4, which ultimately results in a different error:

> $ env LD_PRELOAD=/usr/lib/libcurl.so.3 tsschecker -d iPhone3,1 --list-ios
tsschecker: /usr/lib/libcurl.so.3: version \`CURL_OPENSSL_4\' not found (required by tsschecker)
tsschecker: /usr/lib/libcurl.so.3: version \`CURL_OPENSSL_4\' not found (required by /usr/local/lib/libfragmentzip.so.0)

I'm assuming this is because tsschecker compiled against libcurl4 by default, though I'm not sure how I could fix that.

**Comment by s0uthwest** [comment]
Did you seen note in [ReadMe](https://github.com/tihmstar/tsschecker/blob/master/README.md)?

**Comment by unilock** [comment]
@s0uthwest Yes; I mentioned above that I had followed the guide in the README, which ultimately resulted in the following:

> $ env LD_PRELOAD=/usr/lib/libcurl.so.3 tsschecker -d iPhone3,1 --list-ios
tsschecker: /usr/lib/libcurl.so.3: version `CURL_OPENSSL_4' not found (required by tsschecker)
tsschecker: /usr/lib/libcurl.so.3: version `CURL_OPENSSL_4' not found (required by /usr/local/lib/libfragmentzip.so.0)

**Comment by s0uthwest** [comment]
Hmmmm, very interesting.
Try to compile curl: https://github.com/curl/curl from here and compile TSSChecker.

**Comment by unilock** [comment]
@s0uthwest I've compiled curl from the specified repository, and recompiled both libfragmentzip and tsschecker against the new libcurl. Still, I encounter the same error.

> $ tsschecker -d iPhone3,1 --list-ios
Version: b2ea39564523aaa09478ccd00c9ca811c53479c0 - 281
Segmentation fault (core dumped)

**Comment by djeraseit** [comment]
Looks like it has trouble parsing XML. I'm on linux and using only libcurl4 and libcurl3 is deprecated. I will try the instructions for adding libcurl3 but this should not be necessary in 2020.

```
mmap(NULL, 327680, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa3ad3cc000
openat(AT_FDCWD, "/tmp/tsschecker/iPhone10,3_13.6_17G68", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 4
fstat(4, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
write(4, "<?xml version=\"1.0\" encoding=\"UT"..., 323584) = 323584
munmap(0x7fa3ad3cc000, 327680)          = 0
write(4, "/1Rpfb7/+k2QxBqHUZirvwU58mY=\n\t\t\t"..., 346) = 346
close(4)                                = 0
openat(AT_FDCWD, "/tmp/tsschecker/iPhone10,3_13.6_17G68", O_RDONLY) = 4
fstat(4, {st_mode=S_IFREG|0644, st_size=323930, ...}) = 0
fstat(4, {st_mode=S_IFREG|0644, st_size=323930, ...}) = 0
lseek(4, 323584, SEEK_SET)              = 323584
read(4, "/1Rpfb7/+k2QxBqHUZirvwU58mY=\n\t\t\t"..., 346) = 346
lseek(4, 0, SEEK_SET)                   = 0
brk(0x561258c68000)                     = 0x561258c68000
read(4, "<?xml version=\"1.0\" encoding=\"UT"..., 323584) = 323584
read(4, "/1Rpfb7/+k2QxBqHUZirvwU58mY=\n\t\t\t"..., 4096) = 346
close(4)                                = 0
brk(0x561258c89000)                     = 0x561258c89000
brk(0x561258caa000)                     = 0x561258caa000
brk(0x561258ccb000)                     = 0x561258ccb000
brk(0x561258cec000)                     = 0x561258cec000
brk(0x561258d0d000)                     = 0x561258d0d000
brk(0x561258d2e000)                     = 0x561258d2e000

brk(0x561258d4f000)                     = 0x561258d4f000
brk(0x561258d70000)                     = 0x561258d70000
brk(0x561258d91000)                     = 0x561258d91000
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
+++ killed by SIGSEGV +++
Segmentation fault
root@omega:/media/theodisbutler/RECOVERY/Mobile/tsschecker/tsschecker# ls -lah /tmp/tsschecker/
total 640K
drwx------  2 root root   80 Jul 18 00:34 .
drwxrwxrwt 20 root root  480 Jul 18 00:15 ..
-rw-r--r--  1 root root 317K Jul 17 19:54 iPhone10,3_13.5.1_17F80
-rw-r--r--  1 root root 317K Jul 18 00:34 iPhone10,3_13.6_17G68
```

**Comment by djeraseit** [comment]
Wanted to update. The .plist files completely download.

root@omega:/media/theodisbutler/RECOVERY/Mobile/tsschecker/tsschecker# tsschecker -d iPhone7,2 -l -e 0x6410608f28226 -s
Version: fea67caa58f492b86fbab298e3329dbf5ff835fb - 305
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
[TSSC] manually specified ECID to use, parsed "0x6410608f28226" to dec:1760344035983910 hex:6410608f28226
[TSSC] opening firmware.json
[JSON] counting elements
[JSON] parsing elements
[TSSC] selecting latest version of firmware: 12.4.8
[TSSC] got firmwareurl for iOS 12.4.8 build 16G201
[TSSC] opening Buildmanifest for iPhone7,2_12.4.8_16G201
[LFZP] downloading BuildManifest.plist from http://updates-http.cdn-apple.com/2020SummerFCS/fullrestores/001-11131/71ECCF56-5998-4F84-9386-F91387BC68A5/iPhone_4.7_12.4.8_16G201_Restore.ipsw
100 [===================================================================================================>]
Segmentation fault
root@omega:/media/theodisbutler/RECOVERY/Mobile/tsschecker/tsschecker# ls -lah /tmp/tsschecker/
total 768K
drwx------  2 root root  100 Jul 18 13:14 .
drwxrwxrwt 20 root root  480 Jul 18 13:09 ..
-rw-r--r--  1 root root 317K Jul 17 19:54 iPhone10,3_13.5.1_17F80
-rw-r--r--  1 root root 317K Jul 18 00:34 iPhone10,3_13.6_17G68
-rw-r--r--  1 root root 126K Jul 18 13:14 iPhone7,2_12.4.8_16G201

**Comment by djeraseit** [comment]
```
    Stack trace of thread 75557:
                #0  0x00007f8d2b3e1afd __strcasecmp_l_sse42 (libc.so.6 + 0x182afd)
                #1  0x000055be2f480e58 getBoardconfigFromModel (tsschecker + 0x4e58)
                #2  0x000055be2f48125a getBuildidentity (tsschecker + 0x525a)
                #3  0x000055be2f4824f6 tssrequest (tsschecker + 0x64f6)
                #4  0x000055be2f482a39 isManifestBufSignedForDevice (tsschecker + 0x6a39)
                #5  0x000055be2f483b81 isVersionSignedForDevice (tsschecker + 0x7b81)
                #6  0x000055be2f48074f main (tsschecker + 0x474f)
                #7  0x00007f8d2b2860b3 __libc_start_main (libc.so.6 + 0x270b3)
                #8  0x000055be2f480a7e _start (tsschecker + 0x4a7e)

```
[New LWP 75557]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./tsschecker -d iPhone7,2 -l -e 0x6410608f28226 -s'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strcasecmp_l_sse42 () at ../sysdeps/x86_64/multiarch/strcmp-sse42.S:200
200	../sysdeps/x86_64/multiarch/strcmp-sse42.S: No such file or directory.
```


```

**Comment by djeraseit** [comment]
Using libcurl.so.4 is working on Ubuntu 20.04 LTS (5.4.0-40-generic)
```

[root@omega:/media/theodisbutler/RECOVERY/Mobile/tsschecker/tsschecker# ldd tsschecker
	linux-vdso.so.1 (0x00007ffcf9bbe000)
	libplist.so.3 => /usr/lib/x86_64-linux-gnu/libplist.so.3 (0x00007f084fad3000)
	libfragmentzip.so.0 => /usr/local/lib/libfragmentzip.so.0 (0x00007f084facd000)
	libcurl.so.4 => /usr/local/lib/libcurl.so.4 (0x00007f084f815000)
	libcrypto.so.1.1 => /usr/lib/x86_64-linux-gnu/libcrypto.so.1.1 (0x00007f084f53f000)
	libirecovery.so.1 => /usr/local/lib/libirecovery.so.1 (0x00007f084f535000)
	libm.so.6 => /lib/x86_64-linux-gnu/libm.so.6 (0x00007f084f3e6000)
	libc.so.6 => /lib/x86_64-linux-gnu/libc.so.6 (0x00007f084f1f2000)
	libpthread.so.0 => /lib/x86_64-linux-gnu/libpthread.so.0 (0x00007f084f1cf000)
	libz.so.1 => /lib/x86_64-linux-gnu/libz.so.1 (0x00007f084f1b3000)
	libquiche.so => /usr/src/curl/../quiche/target/release/libquiche.so (0x00007f084eee6000)
	libnghttp2.so.14 => /usr/lib/x86_64-linux-gnu/libnghttp2.so.14 (0x00007f084eebd000)
	libidn2.so.0 => /usr/lib/x86_64-linux-gnu/libidn2.so.0 (0x00007f084ee9d000)
	librtmp.so.1 => /usr/lib/x86_64-linux-gnu/librtmp.so.1 (0x00007f084ee7b000)
	libssh2.so.1 => /usr/lib/x86_64-linux-gnu/libssh2.so.1 (0x00007f084ee4c000)
	libpsl.so.5 => /usr/lib/x86_64-linux-gnu/libpsl.so.5 (0x00007f084ee39000)
	libldap_r-2.4.so.2 => /usr/lib/x86_64-linux-gnu/libldap_r-2.4.so.2 (0x00007f084ede3000)
	liblber-2.4.so.2 => /usr/lib/x86_64-linux-gnu/liblber-2.4.so.2 (0x00007f084edd2000)
	libbrotlidec.so.1 => /usr/lib/x86_64-linux-gnu/libbrotlidec.so.1 (0x00007f084edc3000)
	libdl.so.2 => /lib/x86_64-linux-gnu/libdl.so.2 (0x00007f084edbb000)
	libusb-1.0.so.0 => /lib/x86_64-linux-gnu/libusb-1.0.so.0 (0x00007f084ed9f000)
	/lib64/ld-linux-x86-64.so.2 (0x00007f084fb47000)
	librt.so.1 => /lib/x86_64-linux-gnu/librt.so.1 (0x00007f084ed94000)
	libgcc_s.so.1 => /lib/x86_64-linux-gnu/libgcc_s.so.1 (0x00007f084ed79000)
	libunistring.so.2 => /usr/lib/x86_64-linux-gnu/libunistring.so.2 (0x00007f084ebf7000)
	libgnutls.so.30 => /usr/lib/x86_64-linux-gnu/libgnutls.so.30 (0x00007f084ea1f000)
	libhogweed.so.5 => /usr/lib/x86_64-linux-gnu/libhogweed.so.5 (0x00007f084e9e7000)
	libnettle.so.7 => /usr/lib/x86_64-linux-gnu/libnettle.so.7 (0x00007f084e9ad000)
	libgmp.so.10 => /usr/lib/x86_64-linux-gnu/libgmp.so.10 (0x00007f084e929000)
	libgcrypt.so.20 => /usr/lib/x86_64-linux-gnu/libgcrypt.so.20 (0x00007f084e80b000)
	libresolv.so.2 => /lib/x86_64-linux-gnu/libresolv.so.2 (0x00007f084e7ef000)
	libsasl2.so.2 => /usr/lib/x86_64-linux-gnu/libsasl2.so.2 (0x00007f084e7d0000)
	libgssapi.so.3 => /usr/lib/x86_64-linux-gnu/libgssapi.so.3 (0x00007f084e78b000)
	libbrotlicommon.so.1 => /usr/lib/x86_64-linux-gnu/libbrotlicommon.so.1 (0x00007f084e768000)
	libudev.so.1 => /lib/x86_64-linux-gnu/libudev.so.1 (0x00007f084e73c000)
	libp11-kit.so.0 => /usr/lib/x86_64-linux-gnu/libp11-kit.so.0 (0x00007f084e606000)
	libtasn1.so.6 => /usr/lib/x86_64-linux-gnu/libtasn1.so.6 (0x00007f084e5ee000)
	libgpg-error.so.0 => /lib/x86_64-linux-gnu/libgpg-error.so.0 (0x00007f084e5cb000)
	libheimntlm.so.0 => /usr/lib/x86_64-linux-gnu/libheimntlm.so.0 (0x00007f084e5bf000)
	libkrb5.so.26 => /usr/lib/x86_64-linux-gnu/libkrb5.so.26 (0x00007f084e52c000)
	libasn1.so.8 => /usr/lib/x86_64-linux-gnu/libasn1.so.8 (0x00007f084e485000)
	libcom_err.so.2 => /lib/x86_64-linux-gnu/libcom_err.so.2 (0x00007f084e47c000)
	libhcrypto.so.4 => /usr/lib/x86_64-linux-gnu/libhcrypto.so.4 (0x00007f084e444000)
	libroken.so.18 => /usr/lib/x86_64-linux-gnu/libroken.so.18 (0x00007f084e42b000)
	libffi.so.7 => /usr/lib/x86_64-linux-gnu/libffi.so.7 (0x00007f084e41f000)
	libwind.so.0 => /usr/lib/x86_64-linux-gnu/libwind.so.0 (0x00007f084e3f5000)
	libheimbase.so.1 => /usr/lib/x86_64-linux-gnu/libheimbase.so.1 (0x00007f084e3e1000)
	libhx509.so.5 => /usr/lib/x86_64-linux-gnu/libhx509.so.5 (0x00007f084e393000)
	libsqlite3.so.0 => /usr/local/lib/libsqlite3.so.0 (0x00007f084e086000)
	libcrypt.so.1 => /lib/x86_64-linux-gnu/libcrypt.so.1 (0x00007f084e04b000)

```

**Comment by djeraseit** [comment]
Stack trace:
Core was generated by `./tsschecker -d iPhone7,2 -l -e 0x6410608f28226 -s'.
Program terminated with signal SIGSEGV, Segmentation fault.

```
  Stack trace of thread 75557:
                #0  0x00007f8d2b3e1afd __strcasecmp_l_sse42 (libc.so.6 + 0x182afd)
                #1  0x000055be2f480e58 getBoardconfigFromModel (tsschecker + 0x4e58)
                #2  0x000055be2f48125a getBuildidentity (tsschecker + 0x525a)
                #3  0x000055be2f4824f6 tssrequest (tsschecker + 0x64f6)
                #4  0x000055be2f482a39 isManifestBufSignedForDevice (tsschecker + 0x6a39)
                #5  0x000055be2f483b81 isVersionSignedForDevice (tsschecker + 0x7b81)
                #6  0x000055be2f48074f main (tsschecker + 0x474f)
                #7  0x00007f8d2b2860b3 __libc_start_main (libc.so.6 + 0x270b3)
                #8  0x000055be2f480a7e _start (tsschecker + 0x4a7e)

```
```
Core was generated by `./tsschecker -d iPhone7,2 -l -e 0x6410608f28226 -s'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strcasecmp_l_sse42 () at ../sysdeps/x86_64/multiarch/strcmp-sse42.S:200
200	../sysdeps/x86_64/multiarch/strcmp-sse42.S: No such file or directory.
(gdb) bt
#0  __strcasecmp_l_sse42 () at ../sysdeps/x86_64/multiarch/strcmp-sse42.S:200
#1  0x000055be2f480e58 in getBoardconfigFromModel (model=0x55be313a6fd0 "iPhone7,2") at tsschecker.c:267
#2  0x000055be2f48125a in getBuildidentity (buildManifest=0x55be313bdcf0, model=0x55be313a6fd0 "iPhone7,2", isUpdateInstall=0) at tsschecker.c:353
#3  0x000055be2f4824f6 in tssrequest (tssreqret=tssreqret@entry=0x7fffe3fb8320, 
    buildManifest=buildManifest@entry=0x55be313bea50 "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n<plist version=\"1.0\">\n<dict>\n\t<key>BuildIdentities</key>\n\t"..., 
    devVals=devVals@entry=0x7fffe3fb8470, basebandMode=basebandMode@entry=kBasebandModeWithBaseband) at tsschecker.c:766
#4  0x000055be2f482a39 in isManifestBufSignedForDevice (
    buildManifestBuffer=buildManifestBuffer@entry=0x55be313bea50 "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n<plist version=\"1.0\">\n<dict>\n\t<key>BuildIdentities</key>\n\t"..., 
    devVals=devVals@entry=0x7fffe3fb8470, basebandMode=kBasebandModeWithBaseband) at tsschecker.c:852
#5  0x000055be2f483b81 in isVersionSignedForDevice (firmwareTokens=<optimized out>, versVals=0x7fffe3fb8450, devVals=0x7fffe3fb8470)
    at tsschecker.c:1051
#6  0x000055be2f48074f in main (argc=<optimized out>, argv=<optimized out>) at main.c:434
(gdb) thread apply all bt full

Thread 1 (Thread 0x7f8d2a0b1a00 (LWP 75557)):
#0  __strcasecmp_l_sse42 () at ../sysdeps/x86_64/multiarch/strcmp-sse42.S:200
No locals.
#1  0x000055be2f480e58 in getBoardconfigFromModel (model=0x55be313a6fd0 "iPhone7,2") at tsschecker.c:267
        rt = 0x0
        table = 0x7f8d2b5ab240 <irecv_devices+64>
#2  0x000055be2f48125a in getBuildidentity (buildManifest=0x55be313bdcf0, model=0x55be313a6fd0 "iPhone7,2", isUpdateInstall=0) at tsschecker.c:353
        boardconfig = <optimized out>
#3  0x000055be2f4824f6 in tssrequest (tssreqret=tssreqret@entry=0x7fffe3fb8320, buildManifest=buildManifest@entry=0x55be313bea50 "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n<plist version=\"1.0\">\n<dict>\n\t<key>BuildIdentities</key>\n\t"..., devVals=devVals@entry=0x7fffe3fb8470, basebandMode=basebandMode@entry=kBasebandModeWithBaseband) at tsschecker.c:766
        error = 0
        manifest = 0x55be313bdcf0
        tssparameter = 0x55be313bda40
        tssreq = 0x55be313bda80
        id0 = <optimized out>
        manifestdict = <optimized out>
        sep = <optimized out>
        is64Bit = <optimized out>
#4  0x000055be2f482a39 in isManifestBufSignedForDevice (buildManifestBuffer=buildManifestBuffer@entry=0x55be313bea50 "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n<plist version=\"1.0\">\n<dict>\n\t<key>BuildIdentities</key>\n\t"..., devVals=devVals@entry=0x7fffe3fb8470, basebandMode=kBasebandModeWithBaseband) at tsschecker.c:852
        isSigned = 0
        tssreq = 0x0
        apticket = 0x0
        apticket2 = 0x0
        apticket3 = 0x0
#5  0x000055be2f483b81 in isVersionSignedForDevice (firmwareTokens=<optimized out>, versVals=0x7fffe3fb8450, devVals=0x7fffe3fb8470) at tsschecker.c:1051
        u = 0x55be313bd920
        nocacheorig = 0
        isSigned = -1
        isSignedOne = <optimized out>
        buildManifest = 0x55be313bea50 "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n<plist version=\"1.0\">\n<dict>\n\t<key>BuildIdentities</key>\n\t"...
        urls = 0x55be313bd920
--Type <RET> for more, q to quit, c to continue without paging--
        cursigned = <optimized out>
#6  0x000055be2f48074f in main (argc=<optimized out>, argv=<optimized out>) at main.c:434
        err = 0
        isSigned = 0
        optindex = 0
        opt = <optimized out>
        flags = <optimized out>
        buildmanifest = 0x0
        ecid = 0x7fffe3fba61c "0x6410608f28226"
        apnonce = 0x0
        sepnonce = 0x0
        bbsnum = 0x0
        devVals = {deviceModel = 0x55be313a6fd0 "iPhone7,2", deviceBoard = 0x0, apnonce = 0x0, sepnonce = 0x0, ecid = 1760344035983910, bbgcid = 0, parsedApnonceLen = 0, parsedSepnonceLen = 0, bbsnum = 0x0, bbsnumSize = 0, generator = '\000' <repeats 18 times>, {installType = kInstallTypeDefault, {___pading = 0, isUpdateInstall = 0}}}
        versVals = {version = 0x55be313a49a0 "12.4.8", buildID = 0x0, basebandMode = kBasebandModeWithBaseband, isOta = 0, useBeta = 0}
        firmwareJson = 0x7f8d29ee7010 "{\"devices\":{\"AppleTV2,1\":{\"name\":\"Apple TV 2G\",\"BoardConfig\":\"k66ap\",\"platform\":\"s5l8930x\",\"cpid\":35120,\"bdid\":16,\"firmwares\":[{\"version\":\"7.1.2\",\"buildid\":\"11D258\",\"sha1sum\":\"4724347f2700dfe82fb864ec"...
        firmwareTokens = 0x7f8d29abf010
        rawFilePath = <optimized out>
```

**Comment by djeraseit** [comment]
Adding board type (**-B n61ap**) bypasses this error:

```
root@omega:/media/theodisbutler/RECOVERY/Mobile/tsschecker/tsschecker# ./tsschecker -B n61ap -d iPhone7,2 -l -e 0x6410608f28226 -s
Version: fea67caa58f492b86fbab298e3329dbf5ff835fb - 305
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
[TSSC] manually specified ECID to use, parsed "0x6410608f28226" to dec:1760344035983910 hex:6410608f28226
[TSSC] opening firmware.json
[JSON] counting elements
[JSON] parsing elements
[TSSC] selecting latest version of firmware: 12.4.8
[TSSC] got firmwareurl for iOS 12.4.8 build 16G201
[TSSC] opening Buildmanifest for iPhone7,2_12.4.8_16G201
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
also requesting APTicket for installType=Update
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
[TSSR] User specified doesn't to request a baseband ticket.
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... failure
[Error] ERROR: TSS request failed (status=128, message=An internal error occurred.)
Saved shsh blobs!
Firmware version 12.4.8 16G201 IS signed!

iOS 12.4.8 for device iPhone7,2 IS being signed!
```

**Comment by djeraseit** [comment]
The status=128 failure is because apple returns an empty plist response. Here is what is sent:
