### ISSUE TITLE
Segmentation fault (core dumped) due to strcasecmp() getBoardconfigFromModel in Linux

### ISSUE THREAD

**Issue by djeraseit** [tihmstar/tsschecker#159]
It looks like tsschecker has trouble parsing XML. I'm on linux and using only libcurl4 as libcurl3 not natively available.

```
mmap(NULL, 327680, PROT_READ|PROT_WRITE, MAP_PRIVATE|MAP_ANONYMOUS, -1, 0) = 0x7fa3ad3cc000
openat(AT_FDCWD, "/tmp/tsschecker/iPhone10,3_13.6_17G68", O_WRONLY|O_CREAT|O_TRUNC, 0666) = 4
fstat(4, {st_mode=S_IFREG|0644, st_size=0, ...}) = 0
write(4, "<?xml version=\"1.0\" encoding=\"UT"..., 323584) = 323584
munmap(0x7fa3ad3cc000, 327680)          = 0
write(4, "/1Rpfb7/+k2QxBqHUZirvwU58mY=\n\t\t\t"..., 346) = 346
close(4)                                = 0
openat(AT_FDCWD, "/tmp/tsschecker/iPhone10,3_13.6_17G68", O_RDONLY) = 4
fstat(4, {st_mode=S_IFREG|0644, st_size=323930, ...}) = 0
fstat(4, {st_mode=S_IFREG|0644, st_size=323930, ...}) = 0
lseek(4, 323584, SEEK_SET)              = 323584
read(4, "/1Rpfb7/+k2QxBqHUZirvwU58mY=\n\t\t\t"..., 346) = 346
lseek(4, 0, SEEK_SET)                   = 0
brk(0x561258c68000)                     = 0x561258c68000
read(4, "<?xml version=\"1.0\" encoding=\"UT"..., 323584) = 323584
read(4, "/1Rpfb7/+k2QxBqHUZirvwU58mY=\n\t\t\t"..., 4096) = 346
close(4)                                = 0
brk(0x561258c89000)                     = 0x561258c89000
brk(0x561258caa000)                     = 0x561258caa000
brk(0x561258ccb000)                     = 0x561258ccb000
brk(0x561258cec000)                     = 0x561258cec000
brk(0x561258d0d000)                     = 0x561258d0d000
brk(0x561258d2e000)                     = 0x561258d2e000

brk(0x561258d4f000)                     = 0x561258d4f000
brk(0x561258d70000)                     = 0x561258d70000
brk(0x561258d91000)                     = 0x561258d91000
--- SIGSEGV {si_signo=SIGSEGV, si_code=SI_KERNEL, si_addr=NULL} ---
+++ killed by SIGSEGV +++
Segmentation fault
root@omega:/media/theodisbutler/RECOVERY/Mobile/tsschecker/tsschecker# ls -lah /tmp/tsschecker/
total 640K
drwx------  2 root root   80 Jul 18 00:34 .
drwxrwxrwt 20 root root  480 Jul 18 00:15 ..
-rw-r--r--  1 root root 317K Jul 17 19:54 iPhone10,3_13.5.1_17F80
-rw-r--r--  1 root root 317K Jul 18 00:34 iPhone10,3_13.6_17G68
```

**Comment by djeraseit** [comment]
Wanted to update. The .plist files completely download.

root@omega:/media/theodisbutler/RECOVERY/Mobile/tsschecker/tsschecker# tsschecker -d iPhone7,2 -l -e 0x6410608f28226 -s
Version: fea67caa58f492b86fbab298e3329dbf5ff835fb - 305
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
[TSSC] manually specified ECID to use, parsed "0x6410608f28226" to dec:1760344035983910 hex:6410608f28226
[TSSC] opening firmware.json
[JSON] counting elements
[JSON] parsing elements
[TSSC] selecting latest version of firmware: 12.4.8
[TSSC] got firmwareurl for iOS 12.4.8 build 16G201
[TSSC] opening Buildmanifest for iPhone7,2_12.4.8_16G201
[LFZP] downloading BuildManifest.plist from http://updates-http.cdn-apple.com/2020SummerFCS/fullrestores/001-11131/71ECCF56-5998-4F84-9386-F91387BC68A5/iPhone_4.7_12.4.8_16G201_Restore.ipsw
100 [===================================================================================================>]
Segmentation fault
root@omega:/media/theodisbutler/RECOVERY/Mobile/tsschecker/tsschecker# ls -lah /tmp/tsschecker/
total 768K
drwx------  2 root root  100 Jul 18 13:14 .
drwxrwxrwt 20 root root  480 Jul 18 13:09 ..
-rw-r--r--  1 root root 317K Jul 17 19:54 iPhone10,3_13.5.1_17F80
-rw-r--r--  1 root root 317K Jul 18 00:34 iPhone10,3_13.6_17G68
-rw-r--r--  1 root root 126K Jul 18 13:14 iPhone7,2_12.4.8_16G201

**Comment by djeraseit** [comment]
```
    Stack trace of thread 75557:
                #0  0x00007f8d2b3e1afd __strcasecmp_l_sse42 (libc.so.6 + 0x182afd)
                #1  0x000055be2f480e58 getBoardconfigFromModel (tsschecker + 0x4e58)
                #2  0x000055be2f48125a getBuildidentity (tsschecker + 0x525a)
                #3  0x000055be2f4824f6 tssrequest (tsschecker + 0x64f6)
                #4  0x000055be2f482a39 isManifestBufSignedForDevice (tsschecker + 0x6a39)
                #5  0x000055be2f483b81 isVersionSignedForDevice (tsschecker + 0x7b81)
                #6  0x000055be2f48074f main (tsschecker + 0x474f)
                #7  0x00007f8d2b2860b3 __libc_start_main (libc.so.6 + 0x270b3)
                #8  0x000055be2f480a7e _start (tsschecker + 0x4a7e)

```
[New LWP 75557]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
Core was generated by `./tsschecker -d iPhone7,2 -l -e 0x6410608f28226 -s'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strcasecmp_l_sse42 () at ../sysdeps/x86_64/multiarch/strcmp-sse42.S:200
200	../sysdeps/x86_64/multiarch/strcmp-sse42.S: No such file or directory.
```

**Comment by djeraseit** [comment]
Stack trace:
Core was generated by `./tsschecker -d iPhone7,2 -l -e 0x6410608f28226 -s'.
Program terminated with signal SIGSEGV, Segmentation fault.

```
  Stack trace of thread 75557:
                #0  0x00007f8d2b3e1afd __strcasecmp_l_sse42 (libc.so.6 + 0x182afd)
                #1  0x000055be2f480e58 getBoardconfigFromModel (tsschecker + 0x4e58)
                #2  0x000055be2f48125a getBuildidentity (tsschecker + 0x525a)
                #3  0x000055be2f4824f6 tssrequest (tsschecker + 0x64f6)
                #4  0x000055be2f482a39 isManifestBufSignedForDevice (tsschecker + 0x6a39)
                #5  0x000055be2f483b81 isVersionSignedForDevice (tsschecker + 0x7b81)
                #6  0x000055be2f48074f main (tsschecker + 0x474f)
                #7  0x00007f8d2b2860b3 __libc_start_main (libc.so.6 + 0x270b3)
                #8  0x000055be2f480a7e _start (tsschecker + 0x4a7e)

```
```
Core was generated by `./tsschecker -d iPhone7,2 -l -e 0x6410608f28226 -s'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  __strcasecmp_l_sse42 () at ../sysdeps/x86_64/multiarch/strcmp-sse42.S:200
200	../sysdeps/x86_64/multiarch/strcmp-sse42.S: No such file or directory.
(gdb) bt
#0  __strcasecmp_l_sse42 () at ../sysdeps/x86_64/multiarch/strcmp-sse42.S:200
#1  0x000055be2f480e58 in getBoardconfigFromModel (model=0x55be313a6fd0 "iPhone7,2") at tsschecker.c:267
#2  0x000055be2f48125a in getBuildidentity (buildManifest=0x55be313bdcf0, model=0x55be313a6fd0 "iPhone7,2", isUpdateInstall=0) at tsschecker.c:353
#3  0x000055be2f4824f6 in tssrequest (tssreqret=tssreqret@entry=0x7fffe3fb8320, 
    buildManifest=buildManifest@entry=0x55be313bea50 "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n<plist version=\"1.0\">\n<dict>\n\t<key>BuildIdentities</key>\n\t"..., 
    devVals=devVals@entry=0x7fffe3fb8470, basebandMode=basebandMode@entry=kBasebandModeWithBaseband) at tsschecker.c:766
#4  0x000055be2f482a39 in isManifestBufSignedForDevice (
    buildManifestBuffer=buildManifestBuffer@entry=0x55be313bea50 "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n<plist version=\"1.0\">\n<dict>\n\t<key>BuildIdentities</key>\n\t"..., 
    devVals=devVals@entry=0x7fffe3fb8470, basebandMode=kBasebandModeWithBaseband) at tsschecker.c:852
#5  0x000055be2f483b81 in isVersionSignedForDevice (firmwareTokens=<optimized out>, versVals=0x7fffe3fb8450, devVals=0x7fffe3fb8470)
    at tsschecker.c:1051
#6  0x000055be2f48074f in main (argc=<optimized out>, argv=<optimized out>) at main.c:434
(gdb) thread apply all bt full

Thread 1 (Thread 0x7f8d2a0b1a00 (LWP 75557)):
#0  __strcasecmp_l_sse42 () at ../sysdeps/x86_64/multiarch/strcmp-sse42.S:200
No locals.
#1  0x000055be2f480e58 in getBoardconfigFromModel (model=0x55be313a6fd0 "iPhone7,2") at tsschecker.c:267
        rt = 0x0
        table = 0x7f8d2b5ab240 <irecv_devices+64>
#2  0x000055be2f48125a in getBuildidentity (buildManifest=0x55be313bdcf0, model=0x55be313a6fd0 "iPhone7,2", isUpdateInstall=0) at tsschecker.c:353
        boardconfig = <optimized out>
#3  0x000055be2f4824f6 in tssrequest (tssreqret=tssreqret@entry=0x7fffe3fb8320, buildManifest=buildManifest@entry=0x55be313bea50 "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n<plist version=\"1.0\">\n<dict>\n\t<key>BuildIdentities</key>\n\t"..., devVals=devVals@entry=0x7fffe3fb8470, basebandMode=basebandMode@entry=kBasebandModeWithBaseband) at tsschecker.c:766
        error = 0
        manifest = 0x55be313bdcf0
        tssparameter = 0x55be313bda40
        tssreq = 0x55be313bda80
        id0 = <optimized out>
        manifestdict = <optimized out>
        sep = <optimized out>
        is64Bit = <optimized out>
#4  0x000055be2f482a39 in isManifestBufSignedForDevice (buildManifestBuffer=buildManifestBuffer@entry=0x55be313bea50 "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n<plist version=\"1.0\">\n<dict>\n\t<key>BuildIdentities</key>\n\t"..., devVals=devVals@entry=0x7fffe3fb8470, basebandMode=kBasebandModeWithBaseband) at tsschecker.c:852
        isSigned = 0
        tssreq = 0x0
        apticket = 0x0
        apticket2 = 0x0
        apticket3 = 0x0
#5  0x000055be2f483b81 in isVersionSignedForDevice (firmwareTokens=<optimized out>, versVals=0x7fffe3fb8450, devVals=0x7fffe3fb8470) at tsschecker.c:1051
        u = 0x55be313bd920
        nocacheorig = 0
        isSigned = -1
        isSignedOne = <optimized out>
        buildManifest = 0x55be313bea50 "<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<!DOCTYPE plist PUBLIC \"-//Apple//DTD PLIST 1.0//EN\" \"http://www.apple.com/DTDs/PropertyList-1.0.dtd\">\n<plist version=\"1.0\">\n<dict>\n\t<key>BuildIdentities</key>\n\t"...
        urls = 0x55be313bd920
--Type <RET> for more, q to quit, c to continue without paging--
        cursigned = <optimized out>
#6  0x000055be2f48074f in main (argc=<optimized out>, argv=<optimized out>) at main.c:434
        err = 0
        isSigned = 0
        optindex = 0
        opt = <optimized out>
        flags = <optimized out>
        buildmanifest = 0x0
        ecid = 0x7fffe3fba61c "0x6410608f28226"
        apnonce = 0x0
        sepnonce = 0x0
        bbsnum = 0x0
        devVals = {deviceModel = 0x55be313a6fd0 "iPhone7,2", deviceBoard = 0x0, apnonce = 0x0, sepnonce = 0x0, ecid = 1760344035983910, bbgcid = 0, parsedApnonceLen = 0, parsedSepnonceLen = 0, bbsnum = 0x0, bbsnumSize = 0, generator = '\000' <repeats 18 times>, {installType = kInstallTypeDefault, {___pading = 0, isUpdateInstall = 0}}}
        versVals = {version = 0x55be313a49a0 "12.4.8", buildID = 0x0, basebandMode = kBasebandModeWithBaseband, isOta = 0, useBeta = 0}
        firmwareJson = 0x7f8d29ee7010 "{\"devices\":{\"AppleTV2,1\":{\"name\":\"Apple TV 2G\",\"BoardConfig\":\"k66ap\",\"platform\":\"s5l8930x\",\"cpid\":35120,\"bdid\":16,\"firmwares\":[{\"version\":\"7.1.2\",\"buildid\":\"11D258\",\"sha1sum\":\"4724347f2700dfe82fb864ec"...
        firmwareTokens = 0x7f8d29abf010
        rawFilePath = <optimized out>
```

**Comment by djeraseit** [comment]
Adding board type (**-B n61ap**) bypasses this error:

```
root@omega:/media/theodisbutler/RECOVERY/Mobile/tsschecker/tsschecker# ./tsschecker -B n61ap -d iPhone7,2 -l -e 0x6410608f28226 -s
Version: fea67caa58f492b86fbab298e3329dbf5ff835fb - 305
libfragmentzip version: 0.60-120447d0f410dffb49948fa155467fc5d91ca3c8
[TSSC] manually specified ECID to use, parsed "0x6410608f28226" to dec:1760344035983910 hex:6410608f28226
[TSSC] opening firmware.json
[JSON] counting elements
[JSON] parsing elements
[TSSC] selecting latest version of firmware: 12.4.8
[TSSC] got firmwareurl for iOS 12.4.8 build 16G201
[TSSC] opening Buildmanifest for iPhone7,2_12.4.8_16G201
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
also requesting APTicket for installType=Update
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... success
[TSSR] User specified doesn't to request a baseband ticket.
[TSSR] Request URL set to https://gs.apple.com/TSS/controller?action=2
[TSSR] Sending TSS request attempt 1... failure
[Error] ERROR: TSS request failed (status=128, message=An internal error occurred.)
Saved shsh blobs!
Firmware version 12.4.8 16G201 IS signed!

iOS 12.4.8 for device iPhone7,2 IS being signed!
```
